
if(CMAKE_HOST_SYSTEM_NAME STREQUAL Linux)
    find_program(GCC_Executable Name gcc REQUIRED)
    set(CMAKE_C_COMPILER ${GCC_Executable})

    find_program(G++_Executable Name g++ REQUIRED)
    set(CMAKE_CXX_COMPILER ${G++_Executable})
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL Windows)
    find_program(CL_Executable Name cl REQUIRED)
    set(CMAKE_C_COMPILER ${CL_Executable})
    set(CMAKE_CXX_COMPILER ${CL_Executable})
    find_program(LINKER_Executable Name link REQUIRED)
    set(CMAKE_LINKER ${LINKER_Executable})
    find_program(LIB_Executable Name lib REQUIRED)
    set(CMAKE_AR ${LIB_Executable})
else()
    message(FATAL_ERROR "${CMAKE_HOST_SYSTEM_NAME} is not supported yet !")
endif()

#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
